MaxEventSize = 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data

[Writable]
LogLevel = "INFO"

[Service]
Port = 59900
StartupMsg = "Configuration from config provider"

[MessageBus]
  [MessageBus.Optional]
  ClientId = "device-virtual"
