name: edgex-config-provider-example
base: core22

version: git
summary: Example EdgeX snaps config provider
description: |
  This is an example snap to provide configuration files to EdgeX service snaps.

  For source code and details, refer to:  
  https://github.com/canonical/edgex-config-provider 
  
architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# The consumer plugs can connect to these slots.
# Each source path get mounted as a read-only directory
#   inside the corresponding plug's target path.
slots:
  device-virtual-config:
    interface: content
    source:
      read: 
        - $SNAP/device-virtual/res

# Prepare the config files for slots
parts:
  device-virtual:
    plugin: dump
    # Take config files from the local file system
    source: examples/device-virtual
    # The config files can be pulled from a variety of sources.
    # For example. to take config files from a git repository, i.e. the upstream repo:
    # source: https://github.com/edgexfoundry/device-virtual-go.git
    override-build: |
      TARGET=$CRAFT_PART_INSTALL/device-virtual

      mkdir -p $TARGET
      cp -vr res $TARGET/res
     
