name: edgex-config-provider-example
base: core20

version: "2.3"
summary: Example EdgeX snaps config provider
description: |
  This is an example snap to provide configuration files to EdgeX service snaps.

  For source code and details, refer to:  
  https://github.com/canonical/edgex-config-provider 

grade: stable
confinement: strict

# The consumer plugs can connect to these slots.
# Each source path get mounted as a read-only directory
#   inside the corresponding plug's target path.
slots:
  device-virtual-config:
    interface: content
    source:
      read: 
        - $SNAP/device-virtual/res
  ########################
  # SLOTS FOR SNAP TESTING
  app-service-configurable-config:
    interface: content
    source:
      read: 
        - $SNAP/app-service-configurable/res
  app-rfid-llrp-inventory-config:
    interface: content
    source:
      read: 
        - $SNAP/app-rfid-llrp-inventory/res
  device-gpio-config:
    interface: content
    source:
      read: 
        - $SNAP/device-gpio/res
  device-modbus-config:
    interface: content
    source:
      read: 
        - $SNAP/device-modbus/res
  device-mqtt-config:
    interface: content
    source:
      read: 
        - $SNAP/device-mqtt/res
  device-rest-config:
    interface: content
    source:
      read: 
        - $SNAP/device-rest/res
  device-rfid-llrp-config:
    interface: content
    source:
      read: 
        - $SNAP/device-rfid-llrp/res
  device-snmp-config:
    interface: content
    source:
      read: 
        - $SNAP/device-snmp/res
  device-usb-camera-config:
    interface: content
    source:
      read: 
        - $SNAP/device-usb-camera/res
  device-onvif-camera-config:
    interface: content
    source:
      read: 
        - $SNAP/device-onvif-camera/res

# Prepare the config files for slots
parts:
  device-virtual:
    plugin: dump
    # Take config files from the local file system
    source: examples/device-virtual
    source-depth: 1
    # The config files can be pulled from a variety of sources.
    # For example. to take config files from a git repository, i.e. the upstream repo:
    # source: https://github.com/edgexfoundry/device-virtual-go.git
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-virtual

      mkdir -p $TARGET
      cp -vr res $TARGET/res

      # Change the startup message, for the sake of testing
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  ########################
  # ADDITIONAL PARTS FOR SNAP TESTING
  app-service-configurable:
    plugin: dump
    source: https://github.com/edgexfoundry/app-service-configurable.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/app-service-configurable
      mkdir -p $TARGET
      cp -vr res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  app-rfid-llrp-inventory:
    plugin: dump
    source: https://github.com/edgexfoundry/app-rfid-llrp-inventory.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/app-rfid-llrp-inventory
      mkdir -p $TARGET
      cp -vr res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  device-gpio:
    plugin: dump
    source: https://github.com/edgexfoundry/device-gpio.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-gpio
      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  device-modbus:
    plugin: dump
    source: https://github.com/edgexfoundry/device-modbus-go.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-modbus
      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  device-mqtt:
    plugin: dump
    source: https://github.com/edgexfoundry/device-mqtt-go.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-mqtt
      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  device-rest:
    plugin: dump
    source: https://github.com/edgexfoundry/device-rest-go.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-rest
      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  device-rfid-llrp:
    plugin: dump
    source: https://github.com/edgexfoundry/device-rfid-llrp-go.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-rfid-llrp
      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
      # add devices directory because it doesn't exist upstream
      mkdir -p $TARGET/res/devices
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  device-snmp:
    plugin: dump
    source: https://github.com/edgexfoundry/device-snmp-go.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-snmp
      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  device-usb-camera:
    plugin: dump
    source: https://github.com/edgexfoundry/device-usb-camera.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-usb-camera
      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
  device-onvif-camera:
    plugin: dump
    source: https://github.com/edgexfoundry/device-onvif-camera.git
    source-depth: 1
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-onvif-camera
      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
      $SNAPCRAFT_PROJECT_DIR/amend-startup-msg.sh $TARGET
     