name: edgex-config-provider-example
base: core20

version: "2.3"
summary: Example EdgeX snaps config provider
description: |
  This is an example snap to provide configuration files to EdgeX service snaps.

  For source code and details, refer to:  
  https://github.com/canonical/edgex-config-provider 

grade: stable
confinement: strict

# The consumer plugs can connect to these slots.
# Each source path get mounted as a read-only directory
#   inside the corresponding plug's target path.
slots:
  app-service-configurable-config:
    interface: content
    source:
      read: 
        - $SNAP/app-service-configurable/res
  device-mqtt-config:
    interface: content
    source:
      read: 
        - $SNAP/device-mqtt/res
  device-virtual-config:
    interface: content
    source:
      read: 
        - $SNAP/device-virtual/res

# Prepare the config files for slots
parts:
  app-service-configurable:
    # This example takes source files from the local file system
    plugin: dump
    source: examples/app-service-configurable
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/app-service-configurable

      mkdir -p $TARGET
      cp -vr res $TARGET/res
  device-mqtt:
    # This example takes config files from a git repository, in this case, the upstream repo
    plugin: dump
    source: https://github.com/edgexfoundry/device-mqtt-go.git
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-mqtt

      mkdir -p $TARGET
      cp -vr cmd/res $TARGET/res
  device-virtual:
    # This example takes source files from the local file system
    plugin: dump
    source: examples/device-virtual
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/device-virtual

      mkdir -p $TARGET
      cp -vr res $TARGET/res
